# A Dockerfile to install ISCE3 from source code,
# so that the up-to-date features can be tested.
#
# Instruction
#

FROM oraclelinux:8

LABEL author="OPERA ADT" \
    description="RTC-S1" \
    version="0.4-calval"

RUN yum -y update &&\
    yum -y install curl git make &&\
    adduser rtc_user

USER rtc_user

RUN mkdir -p /home/rtc_user/OPERA &&\
    chmod -R 755 /home/rtc_user

#RUN chown -R rtc_user:rtc_user /home/rtc_user/OPERA &&\

ENV CONDA_PREFIX=/home/rtc_user/miniconda3

# install Miniconda
WORKDIR /home/rtc_user
RUN curl -sSL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o miniconda.sh &&\
    bash miniconda.sh -b -p ${CONDA_PREFIX} &&\
    rm $HOME/miniconda.sh

ENV PATH=${CONDA_PREFIX}/bin:${PATH}
RUN ${CONDA_PREFIX}/bin/conda init bash

# copy RTC and set rtc_user as owner
COPY --chown=rtc_user:rtc_user . /home/rtc_user/OPERA/RTC

# create CONDA environment
RUN conda create --name "RTC" --file /home/rtc_user/OPERA/RTC/Docker/lockfile.lock.calval

SHELL ["conda", "run", "-n", "RTC", "/bin/bash", "-c"]

# Install ISCE3
RUN mkdir -p /home/rtc_user/OPERA/ISCE3/install &&\
    mkdir -p /home/rtc_user/OPERA/ISCE3/build &&\
    cd /home/rtc_user/OPERA/ISCE3/build &&\
    cmake -DCMAKE_INSTALL_PREFIX=/home/rtc_user/OPERA/ISCE3/install -DWITH_CUDA=OFF /home/rtc_user/OPERA/RTC/isce-develop &&\
    make -j32 VERBOSE=ON &&\
    make install &&\
    rm -rf /home/rtc_user/OPERA/ISCE3/build/* &&\
    cd $CONDA_PREFIX/lib &&\
    find /home/rtc_user/OPERA/ISCE3/install/lib64 -name "*.so*" -exec ln -s {} \; &&\
    cd `find $CONDA_PREFIX -name "site-packages"|sort|tail -1` &&\
    find /home/rtc_user/OPERA/ISCE3/install/packages -maxdepth 1 -type d|sort|awk 'NR>1'|xargs -I{} ln -s {}



WORKDIR /home/rtc_user/OPERA

# Install ISCE3


# installing OPERA s1-reader
RUN curl -sSL https://github.com/opera-adt/s1-reader/archive/refs/tags/v0.1.7.tar.gz -o s1_reader_src.tar.gz &&\
    tar -xvf s1_reader_src.tar.gz &&\
    ln -s s1-reader-0.1.7 s1-reader &&\
    rm s1_reader_src.tar.gz &&\
    python -m pip install ./s1-reader

# installing RAiDER
#RUN mkdir RAiDER &&\
#    git clone https://github.com/dbekaert/RAiDER.git RAiDER &&\
#    cd RAiDER &&\
#    git checkout tags/v0.4.2 &&\
#    cd .. &&\
#    python -m pip install ./RAiDER

# installing OPERA RTC
RUN python -m pip install ./RTC &&\
    echo "conda activate RTC" >> /home/rtc_user/.bashrc

WORKDIR /home/rtc_user/scratch

ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "RTC"]
